/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WorkerService } from "../worker.service";
import { WorkerCreateInput } from "./WorkerCreateInput";
import { Worker } from "./Worker";
import { WorkerFindManyArgs } from "./WorkerFindManyArgs";
import { WorkerWhereUniqueInput } from "./WorkerWhereUniqueInput";
import { WorkerUpdateInput } from "./WorkerUpdateInput";
import { SkillFindManyArgs } from "../../skill/base/SkillFindManyArgs";
import { Skill } from "../../skill/base/Skill";
import { SkillWhereUniqueInput } from "../../skill/base/SkillWhereUniqueInput";

export class WorkerControllerBase {
  constructor(protected readonly service: WorkerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Worker })
  async createWorker(@common.Body() data: WorkerCreateInput): Promise<Worker> {
    return await this.service.createWorker({
      data: {
        ...data,

        company: data.company
          ? {
              connect: data.company,
            }
          : undefined,

        employmentStatus: data.employmentStatus
          ? {
              connect: data.employmentStatus,
            }
          : undefined,
      },
      select: {
        budget: true,

        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        employmentStatus: {
          select: {
            id: true,
          },
        },

        id: true,
        isFullTime: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Worker] })
  @ApiNestedQuery(WorkerFindManyArgs)
  async workers(@common.Req() request: Request): Promise<Worker[]> {
    const args = plainToClass(WorkerFindManyArgs, request.query);
    return this.service.workers({
      ...args,
      select: {
        budget: true,

        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        employmentStatus: {
          select: {
            id: true,
          },
        },

        id: true,
        isFullTime: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Worker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async worker(
    @common.Param() params: WorkerWhereUniqueInput
  ): Promise<Worker | null> {
    const result = await this.service.worker({
      where: params,
      select: {
        budget: true,

        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        employmentStatus: {
          select: {
            id: true,
          },
        },

        id: true,
        isFullTime: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Worker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWorker(
    @common.Param() params: WorkerWhereUniqueInput,
    @common.Body() data: WorkerUpdateInput
  ): Promise<Worker | null> {
    try {
      return await this.service.updateWorker({
        where: params,
        data: {
          ...data,

          company: data.company
            ? {
                connect: data.company,
              }
            : undefined,

          employmentStatus: data.employmentStatus
            ? {
                connect: data.employmentStatus,
              }
            : undefined,
        },
        select: {
          budget: true,

          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          employmentStatus: {
            select: {
              id: true,
            },
          },

          id: true,
          isFullTime: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Worker })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWorker(
    @common.Param() params: WorkerWhereUniqueInput
  ): Promise<Worker | null> {
    try {
      return await this.service.deleteWorker({
        where: params,
        select: {
          budget: true,

          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          employmentStatus: {
            select: {
              id: true,
            },
          },

          id: true,
          isFullTime: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/skills")
  @ApiNestedQuery(SkillFindManyArgs)
  async findSkills(
    @common.Req() request: Request,
    @common.Param() params: WorkerWhereUniqueInput
  ): Promise<Skill[]> {
    const query = plainToClass(SkillFindManyArgs, request.query);
    const results = await this.service.findSkills(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        worker: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/skills")
  async connectSkills(
    @common.Param() params: WorkerWhereUniqueInput,
    @common.Body() body: SkillWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skills: {
        connect: body,
      },
    };
    await this.service.updateWorker({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/skills")
  async updateSkills(
    @common.Param() params: WorkerWhereUniqueInput,
    @common.Body() body: SkillWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skills: {
        set: body,
      },
    };
    await this.service.updateWorker({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/skills")
  async disconnectSkills(
    @common.Param() params: WorkerWhereUniqueInput,
    @common.Body() body: SkillWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      skills: {
        disconnect: body,
      },
    };
    await this.service.updateWorker({
      where: params,
      data,
      select: { id: true },
    });
  }
}
