/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Worker } from "./Worker";
import { WorkerCountArgs } from "./WorkerCountArgs";
import { WorkerFindManyArgs } from "./WorkerFindManyArgs";
import { WorkerFindUniqueArgs } from "./WorkerFindUniqueArgs";
import { DeleteWorkerArgs } from "./DeleteWorkerArgs";
import { WorkerService } from "../worker.service";
@graphql.Resolver(() => Worker)
export class WorkerResolverBase {
  constructor(protected readonly service: WorkerService) {}

  async _workersMeta(
    @graphql.Args() args: WorkerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Worker])
  async workers(@graphql.Args() args: WorkerFindManyArgs): Promise<Worker[]> {
    return this.service.workers(args);
  }

  @graphql.Query(() => Worker, { nullable: true })
  async worker(
    @graphql.Args() args: WorkerFindUniqueArgs
  ): Promise<Worker | null> {
    const result = await this.service.worker(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Worker)
  async deleteWorker(
    @graphql.Args() args: DeleteWorkerArgs
  ): Promise<Worker | null> {
    try {
      return await this.service.deleteWorker(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
