/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { EmploymentStatus } from "./EmploymentStatus";
import { EmploymentStatusCountArgs } from "./EmploymentStatusCountArgs";
import { EmploymentStatusFindManyArgs } from "./EmploymentStatusFindManyArgs";
import { EmploymentStatusFindUniqueArgs } from "./EmploymentStatusFindUniqueArgs";
import { DeleteEmploymentStatusArgs } from "./DeleteEmploymentStatusArgs";
import { EmploymentStatusService } from "../employmentStatus.service";
@graphql.Resolver(() => EmploymentStatus)
export class EmploymentStatusResolverBase {
  constructor(protected readonly service: EmploymentStatusService) {}

  async _employmentStatusesMeta(
    @graphql.Args() args: EmploymentStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [EmploymentStatus])
  async employmentStatuses(
    @graphql.Args() args: EmploymentStatusFindManyArgs
  ): Promise<EmploymentStatus[]> {
    return this.service.employmentStatuses(args);
  }

  @graphql.Query(() => EmploymentStatus, { nullable: true })
  async employmentStatus(
    @graphql.Args() args: EmploymentStatusFindUniqueArgs
  ): Promise<EmploymentStatus | null> {
    const result = await this.service.employmentStatus(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EmploymentStatus)
  async deleteEmploymentStatus(
    @graphql.Args() args: DeleteEmploymentStatusArgs
  ): Promise<EmploymentStatus | null> {
    try {
      return await this.service.deleteEmploymentStatus(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
